#!/usr/bin/env bash

# Color definitions
RESET='\033[0m'
BOLD='\033[1m'
GREEN='\033[38;5;46m'
CYAN='\033[38;5;51m'
YELLOW='\033[38;5;226m'
MAGENTA='\033[38;5;201m'
BLUE='\033[38;5;33m'

echo ""
echo -e "${BOLD}${MAGENTA}╔══════════════════════════════════════════════════════════════════════╗${RESET}"
echo -e "${BOLD}${MAGENTA}║                    🏡 NINHO COMMAND CHEATSHEET 🏡                    ║${RESET}"
echo -e "${BOLD}${MAGENTA}╚══════════════════════════════════════════════════════════════════════╝${RESET}"
echo ""
echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${BOLD}${GREEN}📁 FILESYSTEM LAYOUT${RESET}"
echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo ""
echo -e "${CYAN}/home/$USER/${RESET}      → ${BLUE}NVMe SSDs${RESET} (Fast, 1.8TB, Mirrored)"
echo -e "                   Your personal files, configs, code"
echo ""
echo -e "${CYAN}/storage/${RESET}         → ${BLUE}HDDs${RESET} (Large, 14TB, RAIDZ1)"
echo -e "                   Movies, music, photos, backups"
echo ""
echo -e "${YELLOW}Check space:${RESET} ${CYAN}df -h${RESET} or ${CYAN}zfs list${RESET}"
echo ""
echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${BOLD}${GREEN}💾 ZFS COMMANDS${RESET}"
echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo ""
echo -e "${YELLOW}Disk Usage:${RESET}"
echo -e "  ${CYAN}df -h${RESET}                        # Human-readable disk space"
echo -e "  ${CYAN}zfs list${RESET}                     # ZFS datasets and usage"
echo -e "  ${CYAN}ncdu /home/$USER${RESET}             # Interactive disk analyzer"
echo -e "  ${CYAN}du -sh /home/$USER/*${RESET}         # Size of home directories"
echo ""
echo -e "${YELLOW}Snapshots:${RESET}"
echo -e "  ${CYAN}zfs list -t snapshot${RESET}         # List all snapshots"
echo -e "  ${CYAN}ls ~/.zfs/snapshot/${RESET}          # Browse your snapshots"
echo -e "  ${CYAN}cp ~/.zfs/snapshot/NAME/file ./${RESET}  # Restore deleted file"
echo ""
echo -e "${YELLOW}Pool Health:${RESET}"
echo -e "  ${CYAN}sudo zpool status${RESET}            # Check RAID health"
echo -e "  ${CYAN}sudo zpool list${RESET}              # Pool capacity"
echo ""
echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${BOLD}${GREEN}📦 NIXOS & PACKAGES${RESET}"
echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo ""
echo -e "${YELLOW}Install Packages (Your User):${RESET}"
echo -e "  ${CYAN}nano ~/.config/home-manager/home.nix${RESET}"
echo -e "  ${CYAN}home-manager switch${RESET}"
echo ""
echo -e "${YELLOW}Install System Packages (Requires Sudo):${RESET}"
echo -e "  ${CYAN}sudo nano /etc/nixos/configuration.nix${RESET}"
echo -e "  ${CYAN}sudo nixos-rebuild switch${RESET}"
echo ""
echo -e "${YELLOW}Search Packages:${RESET}"
echo -e "  ${CYAN}nix search nixpkgs <package>${RESET}"
echo -e "  ${CYAN}# Example: nix search nixpkgs firefox${RESET}"
echo ""
echo -e "${YELLOW}Temporary Package:${RESET}"
echo -e "  ${CYAN}nix-shell -p <package>${RESET}"
echo -e "  ${CYAN}# Example: nix-shell -p python3${RESET}"
echo ""
echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${BOLD}${GREEN}🔧 SYSTEM MONITORING${RESET}"
echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo ""
echo -e "${CYAN}ninho-status${RESET}           # Complete system health report"
echo -e "${CYAN}htop${RESET}                   # CPU/RAM usage (press F10 to exit)"
echo -e "${CYAN}iotop${RESET}                  # Disk I/O monitor"
echo -e "${CYAN}sudo journalctl -f${RESET}     # Live system logs"
echo -e "${CYAN}sudo systemctl status${RESET}  # Service status"
echo ""
echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${BOLD}${GREEN}🖥️  TMUX (Persistent Sessions)${RESET}"
echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo ""
echo -e "${CYAN}tmux${RESET}                   # Start new session"
echo -e "${CYAN}tmux attach${RESET}            # Attach to existing session"
echo -e "${CYAN}tmux ls${RESET}                # List sessions"
echo ""
echo -e "${YELLOW}Inside tmux:${RESET}"
echo -e "  ${CYAN}Ctrl+b d${RESET}            # Detach (session keeps running)"
echo -e "  ${CYAN}Ctrl+b c${RESET}            # Create new window"
echo -e "  ${CYAN}Ctrl+b n${RESET}            # Next window"
echo -e "  ${CYAN}Ctrl+b p${RESET}            # Previous window"
echo -e "  ${CYAN}Ctrl+b [${RESET}            # Scroll mode (q to exit)"
echo ""
echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${BOLD}${GREEN}🛠️  USEFUL EVERYDAY COMMANDS${RESET}"
echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo ""
echo -e "${CYAN}cd /storage${RESET}            # Go to bulk storage"
echo -e "${CYAN}ls -lah${RESET}                # List files with details"
echo -e "${CYAN}tree${RESET}                   # Show directory structure"
echo -e "${CYAN}mkdir -p path/to/dir${RESET}   # Create nested directories"
echo -e "${CYAN}rsync -av src/ dst/${RESET}    # Copy with progress"
echo -e "${CYAN}tail -f file.log${RESET}       # Follow log file"
echo ""
echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${BOLD}${GREEN}🆘 HELP & DOCUMENTATION${RESET}"
echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo ""
echo -e "${CYAN}man <command>${RESET}          # Manual for any command"
echo -e "${CYAN}<command> --help${RESET}       # Quick help"
echo -e "${CYAN}ninho-cheat${RESET}            # This cheatsheet"
echo -e "${CYAN}ninho-status${RESET}           # System health report"
echo ""
echo -e "${YELLOW}NixOS Resources:${RESET}"
echo -e "  • https://nixos.org/manual/nixos/stable/"
echo -e "  • https://search.nixos.org/packages (package search)"
echo -e "  • https://nix-community.github.io/home-manager/"
echo ""
echo -e "${BOLD}${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo ""
echo -e "${GREEN}💡 Pro tip: Press 'q' to exit most CLI tools (htop, less, man, etc.)${RESET}"
echo ""
