# ============================================================================
# hetzner-hub, Hetzner Cloud VM (public WireGuard hub + tunnel DNS resolver)
# ============================================================================
# Replaces the RPi as the public WireGuard endpoint after the home ISP switch
# removes the public IP. Installed via nixos-anywhere; managed declaratively and
# deployed thereafter with colmena (see flake.nix). See ./README.md for the
# install + cutover procedure.
# ============================================================================
{ pkgs, inputs, ... }:
{
  imports = [
    inputs.disko.nixosModules.disko # provides the `disko` option ./disko.nix sets
    ./disko.nix
    ./hardware-configuration.nix # generated by nixos-anywhere, git-tracked
    ./networking.nix # host net: systemd-networkd, DHCP v4 + static v6
    ./wireguard.nix # WireGuard hub + NAT + public firewall
    ./headscale.nix # self-hosted Tailscale control plane (coexists with wg0)
    ./dns.nix # tunnel-only adblock resolver (options for the module below)
    ../../common/services/unbound-adblock.nix # shared unbound + RPZ definition
  ];

  # Bootloader: legacy BIOS + GRUB. This VM boots in BIOS mode (pre-flight:
  # /sys/firmware/efi absent, GPT carries a BIOS-boot partition), so a
  # systemd-boot/UEFI setup would leave it unbootable. disko creates the EF02
  # BIOS-boot partition GRUB embeds into AND registers the disk in
  # boot.loader.grub.devices, so we only enable GRUB here.
  boot.loader.grub = {
    enable = true;
    configurationLimit = 10; # cap generations
  };

  time.timeZone = "Europe/Lisbon";
  i18n.defaultLocale = "en_US.UTF-8";

  nix.settings.experimental-features = [
    "nix-command"
    "flakes"
  ];

  # Key-only root SSH (public, on port 22). Independent of wg0, so a WireGuard
  # mistake can never lock you out. Same key as the rest of the fleet.
  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "prohibit-password";
      PasswordAuthentication = false;
    };
  };
  users.users.root.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHKTf4Bb2BBymwZvxPtxEefspOPTACPn3HqrRiWAMJEJ armandoifsantos@gmail.com"
  ];

  environment.systemPackages = with pkgs; [
    wireguard-tools # wg show, debugging the hub
    dnsutils # dig, verifying the resolver
    git
    neovim
  ];

  # First install of this machine was on 26.05; leave as-is (see manual).
  system.stateVersion = "26.05";
}
